name: MainBuild

on:
  push:
    branches: [ main5 ]
    paths-ignore: 
      - '**/README.md'
  pull_request:
    branches: [ main5 ]

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'src'

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
      # Restore nuget packages
    - name: Restore dependencies
      run: dotnet restore
      
      # build the source
    - name: Build
      run: dotnet build --no-restore
      
      # Run the unit tests
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
      # Publish to NuGet
    - name: publish on version change
      id: publish_nuget
      # Using forked version of publish-nuget
      # https://github.com/brandedoutcast/publish-nuget/issues/76
      uses: alirezanet/publish-nuget@v3.0.4
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: src/GoogleSheetsWrapper/GoogleSheetsWrapper.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: true
