name: Build and Tests

on:  
  push:
    branches: [ main ]
    paths-ignore: 
      - '**/README.md'
  pull_request:
    branches: [ main ]
    paths-ignore: 
      - '**/README.md'

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore GoogleSheetsWrapper.sln

      - name: Build Solution
        run: |
          msbuild.exe GoogleSheetsWrapper.sln /p:platform="Any CPU" /p:configuration="Release"
        
      - name: Run Tests
        run: vstest.console.exe .\GoogleSheetsWrapper.Tests\bin\Release\net48\GoogleSheetsWrapper.Tests.dll
